# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: lime blog
email: limedevelopments@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>The blog for SW dev.</h3>Hope you enjoy it!"
<div class="portfolio-container">
    <iframe src="http://www.youtube.com/embed/4aQwT3n2c1Q" height="315" width="560" allowfullscreen="" frameborder="0">
    </iframe>
</div>

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://lime.dev" # the base hostname & protocol for your site
github_username: lime-developments

# Build settings
markdown: kramdown
